webapp/models.py
import requests
from bs4 import BeautifulSoup


list_of_interest = [
'Название марки',
'Название модели',
'Название комплектации',
'Период выпуска',
'Тип привода',
'Тип кузова',
'Тип трансмиссии',
'Объем двигателя, куб.см',
'Страна сборки',
'Марка двигателя',
'Максимальная мощность, л.с. (кВт) при об./мин.',
'Максимальный крутящий момент, Н*м (кг*м) при об./мин.',
'Тип двигателя',
'Используемое топливо',
'Расход топлива в городском цикле, л/100 км',
'Расход топлива за городом, л/100 км',
'Расход топлива в смешанном цикле, л/100 км',
'Передняя подвеска',
'Задняя подвеска',
# 'Шины',
'Передние колеса',
'Задние колеса',
# 'Микроклимат салона',
'Кондиционер',
# 'Салонный фильтр',
# 'Климат-контроль',
# 'Средняя стоимость'
]


def get_html(url):
    try:
        result = requests.get(url)
        result.raise_for_status()
        return result.text
    except(requests.RequestException, ValueError):
        print('Сетевая ошибка')
        return False


def get_auto_specifications(html):

    characteristics = {}
    
    soup = BeautifulSoup(html, 'html.parser')
    path_line = soup.find_all(class_="b-breadcrumbs__item")

    characteristics['Название марки'] = path_line[2].text
    characteristics['Название модели'] = path_line[3].text

    table1 = soup.find_all(class_='b-table b-table_mobile-size-s b-table_text-size-s b-table_text-left')[0]

    row_class_ = 'b-table__row b-table__row_padding_l-r-size-xs '+\
               'b-table__row_cols_2 b-table__row_border_bottom b-table__row_border_light '+\
               'b-table__row_padding_t-b-size-s b-table_align_top'

    for row in table1.find_all('tr', class_=row_class_):
        key = row.find_all('td')[0].text
        value = row.find_all('td')[1].text
        if key in ['Передние колеса','Задние колеса']:
            value = value.split('Отзывы')[0]
        characteristics[key] = value.strip('\n ')
    
    return {key:value for key, value in characteristics.items() if key in list_of_interest}


if __name__ == "__main__":

    html = get_html("https://www.drom.ru/catalog/ford/focus/156523/")

    if html:
        characteristics = get_auto_specifications(html)

webapp/news/models.py
from webapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published_date = db.Column(db.String, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return '<News {} {}>'.format(self.title, self.url)

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'
    
    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField('Отправить', render_kw={"class": "btn btn-dark"})

webapp/__init__.py
from flask import Flask, render_template, flash, redirect, url_for
from flask_login import LoginManager, current_user, login_required
from webapp.user.forms import LoginForm
from webapp.db import db
from webapp.user.models import User


from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint
from webapp.user.views import blueprint as user_blueprint

def create_app():
    app = Flask(__name__)
    app.config.from_pyfile("config.py")
    db.init_app(app)
    
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)
    app.register_blueprint(user_blueprint)
    


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
    

    return app

webapp/admin/views.py
from flask import Blueprint
from flask_login import current_user, login_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@login_required
def admin_index():
    if current_user.is_admin:
        return 'Привет админ'
    else:
        return 'Ты не админ!'

webapp/news/views.py
from flask import Blueprint, render_template

from webapp.news.models import News

blueprint = Blueprint('news', __name__)


@blueprint.route("/")
def main():
    news_list = News.query.limit(5).all()
    return render_template('news/index.html', news_list = news_list)

webapp/user/views.py
from webapp.user.forms import LoginForm
from webapp.user.models import User
from flask_login import LoginManager, current_user, login_required, login_user, logout_user
from flask import Blueprint, render_template, flash, redirect, url_for

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('news.main'))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы вошли на сайт')
            return redirect(url_for('news.main'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

            
@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы не авторизованы')
    return redirect(url_for('news.main'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title> Car compare </title>
  </head>
  <body>                
    <div class="container-fluid">
    {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
</div>
</body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title> Car compare </title>
  </head>
  <body>                
    <div class="header-h1">
        <h1> Выбор подержанного авто </h1>
    </div>  
    <div class="container-fluid">
        <div class="row"> 
            <div class="col-sm-9"> 
                <table class="table table-bordered table-hover">
                    <thead class = "thead-dark">
                        <tr>
                        <th scope="col"> Характеристики </th>
                        <th scope="col"> Свой автомобиль </th>
                        <th scope="col"> Вариант 1</th>
                        <th scope="col"> Вариант 2 </th>
                        <th scope="col"> Вариант 3 </th>
                        <th scope="col"> Вариант 4 </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                        <th scope="row"> Марка </th>
                        <td> Ford </td>
                        <td> Nissan </td>
                        <td> Dodge </td>
                        <td> Lada </td>
                        <td> Kia </td>
                        </tr>
                        <tr>
                        <th scope="row"> Модель </th>
                        <td> Focus </td>
                        <td> Tiida </td>
                        <td> Challenger </td>
                        <td> 2106 </td>
                        <td> Optima </td>
                        </tr>
                        <tr>
                        <th scope="row"> Поколение </th>
                        <td> II </td>
                        <td> I </td>
                        <td> III </td>
                        <td> I </td>
                        <td> III </td>
                        </tr> 
                        <tr>
                        <th scope="row"> Комплектакция </th>
                        <td> 1.6 AT Comfort  </td>
                        <td> 1.6 AT Elegance </td>
                        <td> 3.6 AT </td>
                        <td> 1.3 л, 64 л.с. </td>
                        <td> 2.4 AT Luxe </td>
                        </tr>                        
                        <tr>
                        <th scope="row"> Средний расход топлива на 100 км (л) </th>
                        <td> 7,7 </td>
                        <td> 7,4  </td>
                        <td> 12,0 </td>
                        <td> 9.5 </td>
                        <td> 8,1 </td>
                        </tr>
                        <th scope="row"> Средняя стоимость авто (руб) </th>
                        <td> 400.000 </td>
                        <td> 330.000 </td>
                        <td> 1.400.000 </td>
                        <td> 40.000 </td>
                        <td> 890.000 </td>
                        </tr>
                        <tr>
                        <th scope="row"> Стоимость топлива на 30000км (руб) </th>
                        <td> 115.500 </td>
                        <td> 111.000 </td>
                        <td> 180.000 </td>
                        <td> 142.500 </td>
                        <td> 121.500 </td>
                        </tr>
                        <th scope="row"> Стоимость налога в Мск (руб) </th>
                        <td> 2.000 </td>
                        <td> 2.000 </td>
                        <td> 18.750 </td>
                        <td> 1.400 </td>
                        <td> 9.000 </td>
                        </tr>
                        <th scope="row"> Стоимость ОСАГО (руб) </th>
                        <td> 3500 </td>
                        <td> 3500 </td>
                        <td> 38000 </td>
                        <td> 1800 </td>
                        <td> 24000 </td>
                        </tr>                        
                    </tbody>
                </table>
            </div>
            <div class="col-sm-3">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
                <div class="col-sm-3-news">
                    <div class="news-h3">
                        <h3> новости ГИБДД </h3>
                    </div>
                    <div class="news-h6">
                        {% for news in news_list %}
                        <h6><a href = "{{ news.url }}"> {{ news.title }} </a></h6>
                        <!-- <p> {{ news.published_date }}</p> -->
                        {% endfor%}
                    </div>   
                </div>
            </div>
        </div>
        <div class="row">
            <div class=col-12>
                <footer>                       
                    <div class="footer-1">
                        <h1> © 2019 Copyright: 
                            <a href="https://www.instagram.com/jssemeone/"> 7on-off </a> &
                            <a href="https://www.instagram.com/tattis_beads/"> Tatti </a>
                        </h1>
                    </div> 
                </footer>
            </div> 
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
</div>
</body>
</html>

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <title> Car compare </title>
  </head>
  <body>                
    <div class="header-h1">
        <h1> {{ page_title }} </h1>
    </div>  
    <div class="container-fluid">
        <div class="row"> 
            <div class="col-sm-4">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
                <form action="{{ url_for('user.process_login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username.label }}
                        {{ form.username() }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.remember_me() }}
                        {{ form.remember_me.label(class_='form-check-label') }}
                    </div>
                    {{ form.submit }}
                </form>
            
            </div>
            <div class="col-sm-8">
                
            </div>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
</div>
</body>
</html>

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}    
    <div class="header-h1">
        <h1> Выбор подержанного авто </h1>
    </div>  
    <div class="container-fluid">
        <div class="row"> 
            <div class="col-sm-9"> 
                <table class="table table-bordered table-hover">
                    <thead class = "thead-dark">
                        <tr>
                        <th scope="col"> Характеристики </th>
                        <th scope="col"> Свой автомобиль </th>
                        <th scope="col"> Вариант 1</th>
                        <th scope="col"> Вариант 2 </th>
                        <th scope="col"> Вариант 3 </th>
                        <th scope="col"> Вариант 4 </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                        <th scope="row"> Марка </th>
                        <td> Ford </td>
                        <td> Nissan </td>
                        <td> Dodge </td>
                        <td> Lada </td>
                        <td> Kia </td>
                        </tr>
                        <tr>
                        <th scope="row"> Модель </th>
                        <td> Focus </td>
                        <td> Tiida </td>
                        <td> Challenger </td>
                        <td> 2106 </td>
                        <td> Optima </td>
                        </tr>
                        <tr>
                        <th scope="row"> Поколение </th>
                        <td> II </td>
                        <td> I </td>
                        <td> III </td>
                        <td> I </td>
                        <td> III </td>
                        </tr> 
                        <tr>
                        <th scope="row"> Комплектакция </th>
                        <td> 1.6 AT Comfort  </td>
                        <td> 1.6 AT Elegance </td>
                        <td> 3.6 AT </td>
                        <td> 1.3 л, 64 л.с. </td>
                        <td> 2.4 AT Luxe </td>
                        </tr>                        
                        <tr>
                        <th scope="row"> Средний расход топлива на 100 км (л) </th>
                        <td> 7,7 </td>
                        <td> 7,4  </td>
                        <td> 12,0 </td>
                        <td> 9.5 </td>
                        <td> 8,1 </td>
                        </tr>
                        <th scope="row"> Средняя стоимость авто (руб) </th>
                        <td> 400.000 </td>
                        <td> 330.000 </td>
                        <td> 1.400.000 </td>
                        <td> 40.000 </td>
                        <td> 890.000 </td>
                        </tr>
                        <tr>
                        <th scope="row"> Стоимость топлива на 30000км (руб) </th>
                        <td> 115.500 </td>
                        <td> 111.000 </td>
                        <td> 180.000 </td>
                        <td> 142.500 </td>
                        <td> 121.500 </td>
                        </tr>
                        <th scope="row"> Стоимость налога в Мск (руб) </th>
                        <td> 2.000 </td>
                        <td> 2.000 </td>
                        <td> 18.750 </td>
                        <td> 1.400 </td>
                        <td> 9.000 </td>
                        </tr>
                        <th scope="row"> Стоимость ОСАГО (руб) </th>
                        <td> 3500 </td>
                        <td> 3500 </td>
                        <td> 38000 </td>
                        <td> 1800 </td>
                        <td> 24000 </td>
                        </tr>                        
                    </tbody>
                </table>
            </div>
            <div class="col-sm-3">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
                <div class="col-sm-3-news">
                    <div class="news-h3">
                        <h3> новости ГИБДД </h3>
                    </div>
                    <div class="news-h6">
                        {% for news in news_list %}
                        <h6><a href = "{{ news.url }}"> {{ news.title }} </a></h6>
                        <!-- <p> {{ news.published_date }}</p> -->
                        {% endfor%}
                    </div>   
                </div>
            </div>
        </div>
        <div class="row">
            <div class=col-12>
                <footer>                       
                    <div class="footer-1">
                        <h1> © 2019 Copyright: 
                            <a href="https://www.instagram.com/jssemeone/"> 7on-off </a> &
                            <a href="https://www.instagram.com/tattis_beads/"> Tatti </a>
                        </h1>
                    </div> 
                </footer>
            </div> 
        </div>
    </div>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %} 
    <div class="header-h1">
        <h1> {{ page_title }} </h1>
    </div>  
    <div class="container-fluid">
        <div class="row"> 
            <div class="col-sm-4">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                    </div>
                    {% endif %}
                {% endwith %}
                <form action="{{ url_for('user.process_login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username.label }}
                        {{ form.username() }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.remember_me() }}
                        {{ form.remember_me.label(class_='form-check-label') }}
                    </div>
                    {{ form.submit }}
                </form>
            
            </div>
            <div class="col-sm-8">
                
            </div>
        </div>
    </div>
{% endblock %}